- hosts: database
  become: yes
  gather_facts: yes
  vars_files:
    - secrets.yml
  roles:
    - postgresql_setup

- hosts: production
  become: yes
  vars_files:
    - secrets.yml
  roles:
    - app

